### PR TITLE
feat: Added github workflow greetings

### LINKED ISSUE #20: [Feature]: Add the GitHub action workflow for greeting contributors
# Description:
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull requests (PR) and issue creators, fostering a welcoming environment.

# Proposed Changes:
Implement a GitHub Action workflow that triggers new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Please assign me this issue under IWOC**

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
Closes #20 

# Changes:
Implemented a GitHub Action workflow that triggers new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
@NehaVns Could you please review, today is the last day of IWOC

**Comment by NehaVns** [comment]
ok @JiyaGupta-cs

**Comment by NehaVns** [comment]
i am reopening this issue. That that it is not working properly

**Comment by JiyaGupta-cs** [comment]
@NehaVns How did you test this?

**Comment by JiyaGupta-cs** [comment]
@NehaVns It would work properly maybe you did not get the message on the opening issue since you are not opening it for the first time. It is Only for new comers.

**Comment by NehaVns** [comment]
ok got it.
I'll close the issue

**Pull request merged**
